### ISSUE TITLE
HerdsPanic error

### ISSUE THREAD

**Issue by frogglen** [Sideways-Sky/HerdsPanic#1]
[15:42:40 WARN]: [HerdsPanic] Task #17515021 for HerdsPanic v1.1 generated an exception
java.lang.NoClassDefFoundError: org/bukkit/craftbukkit/v1_21_R1/entity/CraftEntity
        at HerdsPanic-1.1.jar/net.sideways_sky.herdspanic.HerdsPanic.lambda$onEntityDamageByEntity$2(HerdsPanic.java:51) ~[HerdsPanic-1.1.jar:?]
        at org.bukkit.craftbukkit.scheduler.CraftTask.run(CraftTask.java:78) ~[leaf-1.21.3.jar:1.21.3-DEV-0bf20fe]
        at org.bukkit.craftbukkit.scheduler.CraftScheduler.mainThreadHeartbeat(CraftScheduler.java:474) ~[leaf-1.21.3.jar:1.21.3-DEV-0bf20fe]
        at net.minecraft.server.MinecraftServer.tickChildren(MinecraftServer.java:1807) ~[leaf-1.21.3.jar:1.21.3-DEV-0bf20fe]
        at net.minecraft.server.MinecraftServer.tickServer(MinecraftServer.java:1680) ~[leaf-1.21.3.jar:1.21.3-DEV-0bf20fe]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1350) ~[leaf-1.21.3.jar:1.21.3-DEV-0bf20fe]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:330) ~[leaf-1.21.3.jar:1.21.3-DEV-0bf20fe]
        at java.base/java.lang.Thread.run(Thread.java:1583) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.bukkit.craftbukkit.v1_21_R1.entity.CraftEntity
        ... 8 more

**Comment by AnsonEyre** [comment]
This provides no context. i need more info to help you. To start, what server version and type are you using?

**Comment by frogglen** [comment]
> This provides no context. i need more info to help you. To start, what server version and type are you using?

i´m using leaf-1.21.3-DEV-0bf20fe

I just installed the plugin and when I attack an animal I get this error.

**Comment by frogglen** [comment]
> This provides no context. i need more info to help you. To start, what server version and type are you using?

any news?
